# Configuration for Breakdown Prediction Script
holidays:
  - "2024-01-26"
  - "2024-03-03"
  - "2024-05-01"
  - "2024-08-15"
  - "2024-10-02"
prediction_days: 7
min_breakdown_hours: 2
shift_hours:
  A: [6, 14]
  B: [14, 22]
  C: [22, 6]